use_frameworks!

target 'RxShortcuts_Example' do
  pod 'RxShortcuts/RxCocoa', :path => '../'

  target 'RxShortcuts_Tests' do
    inherit! :search_paths    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'Debug'
                config.build_settings['ENABLE_TESTABILITY'] = 'YES'
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
end
